stack: vrfinland/wiki
description: |
  VR Finland Ry wiki.
version: '1.0'
services:
  db:
    image: mariadb
    stateful: true
    ports: []
    volumes: []
    environment:
      - MYSQL_DATABASE=wiki
      - MYSQL_ROOT_PASSWORD=wiki
    extends:
      file: docker-compose.yml
      service: db
  mediawiki:
    image: image-registry.leonidasoy.fi/vrfinland-mediawiki:latest
    ports: []
    volumes: []
    extends:
      file: docker-compose.yml
      service: mediawiki
    depends_on:
      - db
    links:
      - db
    environment:
      - MEDIAWIKI_DB_HOST=db:3306
      - MEDIAWIKI_DB_NAME=wiki
      - MEDIAWIKI_DB_PASSWORD=wiki
      - KONTENA_LB_MODE=http
      - KONTENA_LB_BALANCE=roundrobin
      - KONTENA_LB_INTERNAL_PORT=5601
      - KONTENA_LB_VIRTUAL_HOSTS=vrfinlandwiki.leonidasoy.fi
      - "KONTENA_LB_CUSTOM_SETTINGS=redirect scheme https if !{ ssl_fc }"
